# Generated by Django 5.2 on 2025-05-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_login_id_alter_login_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=10)),
                ('emailaddress', models.EmailField(max_length=100)),
                ('complaint', models.CharField(max_length=5000)),
                ('complaintdate', models.CharField(max_length=30)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=10)),
                ('emailaddress', models.EmailField(max_length=100)),
                ('feedback', models.CharField(max_length=5000)),
                ('feedbackdate', models.CharField(max_length=30)),
            ],
        ),
    ]
