# Generated by Django 5.2 on 2025-05-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custapp', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
