# Generated by Django 5.2 on 2025-05-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custapp', '0004_booking_days_booking_distance_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
